### ISSUE TITLE
Add @Generated on generated query beans

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/querybean-generator#24]

**Comment by soberich** [comment]
@rbygrave just to ping that `@Generated` could be missing. I am not sure if generation process checks if it is available or not.
see relevant expl. http://mapstruct.org/documentation/dev/reference/html/#_using_mapstruct_on_java_9
EDIT:
I meant is `@javax.annotation.Generated` artifact `javax.annotation:javax.annotation-api` is available at all.

**Comment by rbygrave** [comment]
> If the @Generated annotation is not available, MapStruct will detect this situation and not add it to generated mappers.

Ok darn.  We are not doing that ... we are adding it regardless so we will have a problem with that.

Thanks!

**Comment by soberich** [comment]
@rbygrave Hey Rob. I initially posted, wrong stuff. Thanks again!
EDIT: The issue was that. 
I stumbled upon some of assoc querybeans are not "changed" CVS said. It turned out, Querybeans in assoc folder are not deleted at anytime, and when you simply rename some entity or embeddable assoc folder keeps the old generated beans as well. Funny enough, beans under the main (e.g. just `... .query`) package magically was never renamed (by us apparently), so those unchanged beans only appeared under assoc folder and all was `Embeddables`. For the story.

**Comment by rbygrave** [comment]
Ok cool - thanks.
